### PR TITLE
Added tests for precedence

### PR DESCRIPTION
**Pull request by dbaumgarten**
These are the tests I used back than to figure out ingame precedence.
Converted to runnable tests and veryfied to work ingame.
(No yasm here. Sorry.)

### CODE REVIEW

**Comment by dbaumgarten** [comment]
Do NOT merge for now.
I found some issues I have to look into first.

**Comment by dbaumgarten** [comment]
I removed the test-cases that use the factorial-operator on bracketed expressions, as this seems to be a syntax-error.
Also, the not-operator is kinda broken. I changed the tests involving "not" to work around that issue.

I guess now the tests are as good as it gets with that damn broken ingame parser.
Also, I retested them ingame. Seems to work fine.
You can now merge it if you like.

**Comment by martindevans** [comment]
## Notes to self

 - Precedence5 should be duplicated for every single keyword op.
   - [x] Not
 - [x] Before passing Precedence2 there needs to be an entire acid test suite for the behaviour of sqrt. Done: https://github.com/martindevans/Yolol-Acid-Test/blob/master/acid_sqrt.yolol

**Comment by martindevans** [comment]
Note to self: Before passing Precedence2 there needs to be an entire acid test suite for the behaviour of sqrt.

**Comment by dbaumgarten** [comment]
"Not" is not a "normal" keyword-op (it has different precedence than for example sqrt) and it is bugged.
That's why there are so many test for it.

**Pull request merged**
